"""Upgrade practice_record table with quiz_data and ai_feedback columns

Revision ID: 0b7793e3eff8
Revises: 2dbfc76781d7
Create Date: 2026-01-05 22:08:29.409273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7793e3eff8'
down_revision = '2dbfc76781d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_intro', sa.String(length=255), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_prompts')
    # ### end Alembic commands ###
