"""初始化教辅系统数据库：创建用户/课程/作业表

Revision ID: 153213929a19
Revises: b40996a85f6b
Create Date: 2025-12-29 21:28:07.878925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153213929a19'
down_revision = 'b40996a85f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
