"""Upgrade practice_record table with quiz_data and ai_feedback columns

Revision ID: 830d0e772883
Revises: 9446c573cf01
Create Date: 2026-01-02 16:44:46.565367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '830d0e772883'
down_revision = '9446c573cf01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_data', sqlite.JSON(), nullable=False))
        batch_op.add_column(sa.Column('ai_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_feedback', sa.Text(), nullable=True))
        batch_op.drop_column('is_correct')
        batch_op.drop_column('quiz_type')
        batch_op.drop_column('quiz_question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_question', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('quiz_type', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('is_correct', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('ai_feedback')
        batch_op.drop_column('ai_grade')
        batch_op.drop_column('quiz_data')

    # ### end Alembic commands ###
