"""Add GradingRole model and update others

Revision ID: f6008bc91c23
Revises: 92a061a2bd1d
Create Date: 2026-01-12 15:05:05.323420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f6008bc91c23'
down_revision = '92a061a2bd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_prompts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_prompts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('role_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=32), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('short_intro', sa.VARCHAR(length=255), nullable=True),
    sa.Column('prompt_template', sa.TEXT(), nullable=False),
    sa.Column('skills', sqlite.JSON(), nullable=True),
    sa.Column('use_count', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
